### ISSUE TITLE
BottomSheet crashes when there is no SheetDetent.Hidden in the list of detents

### ISSUE THREAD

**Issue by OleksiiMatiash** [composablehorizons/compose-unstyled#39]
I'm trying to implement bottom sheet with two states: fully expanded, and half-hidden, without possibility to hide it completely. To achieve it I'm creating sheet state without SheetDetent.Hidden in the detents list:
```
    val peek = SheetDetent(identifier = "peek") { _, _ -> 100.dp }

    val sheetState = rememberModalBottomSheetState(
        initialDetent = peek,
        detents = listOf(peek, SheetDetent.FullyExpanded)
    )

    ModalBottomSheet(state = sheetState) { }
```
However it crashes:
```
java.lang.IllegalStateException: The initialDetent hidden was not part of the included detents while creating the sheet's state.
at com.composables.core.BottomSheetState.<init>(BottomSheet.kt:143)
at com.composables.core.BottomSheetKt.rememberBottomSheetState$lambda$17(BottomSheet.kt:85)
at com.composables.core.BottomSheetKt.$r8$lambda$HOlp03M64Z9EpLpUe6obdQw4518(Unknown Source:0)
at com.composables.core.BottomSheetKt$$ExternalSyntheticLambda12.invoke(D8$$SyntheticClass:0)
at androidx.compose.runtime.saveable.RememberSaveableKt.rememberSaveable(RememberSaveable.kt:89)
at com.composables.core.BottomSheetKt.rememberBottomSheetState(BottomSheet.kt:67)
at com.composables.core.ModalBottomSheetKt.rememberModalBottomSheetState(ModalBottomSheet.kt:42)
```
Maybe there is another way to achieve this result, but I was unable to find it. If so, please point me in the correct direction.
Thank you.

Lib version is the latest available: 1.18.1

**Comment by alexstyl** [comment]
Thanks for reporting this issue. It is now fixed in [1.18.2](https://github.com/composablehorizons/compose-unstyled/releases/tag/1.18.2). Keep in mind that it might take a while until it is available on Maven Central.

Also, keep in mind that a ModalBottomSheet currently always includes a Hidden detent. You can always disable dragging if you do not want it to be dismissable by passing `enabled = false` to the sheet.
